export const data = [
  {
    id: 1,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "done",
    attempts: 3,
  },
  {
    id: 2,
    questiontype: "FreeChoice",
    answer: "",
    title: "",
    isflag: false,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 3,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 5,
  },
  {
    id: 4,
    questiontype: "Equation",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 1,
  },
  {
    id: 5,
    questiontype: "SortingQuestion",
    answer: "",
    title: "",
    isflag: false,
    progress: "notdone",
    attempts: 1,
  },
  {
    id: 6,
    questiontype: "SingleChoiceQuestion",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 7,
    questiontype: "FillInTheBlank",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 2,
  },
  {
    id: 8,
    questiontype: "MatrixSortingQuestion",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 2,
  },
  {
    id: 9,
    questiontype: "MultipleChoice",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 10,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 3,
  },
  {
    id: 11,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 12,
    questiontype: "FreeChoice",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 5,
  },
  {
    id: 13,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 14,
    questiontype: "Equation",
    answer: "",
    title: "",
    isflag: true,
    progress: "done",
    attempts: 4,
  },
  {
    id: 15,
    questiontype: "SortingQuestion",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 16,
    questiontype: "SingleChoiceQuestion",
    answer: "",
    title: "",
    isflag: true,
    progress: "done",
    attempts: 4,
  },
  {
    id: 17,
    questiontype: "FillInTheBlank",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 18,
    questiontype: "MatrixSortingQuestion",
    answer: "",
    title: "",
    isflag: false,
    progress: "done",
    attempts: 4,
  },
  {
    id: 19,
    questiontype: "MultipleChoice",
    answer: "",
    title: "",
    isflag: false,
    progress: "notdone",
    attempts: 6,
  },
  {
    id: 20,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "done",
    attempts: 4,
  },
  {
    id: 21,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "done",
    attempts: 3,
  },
  {
    id: 22,
    questiontype: "FreeChoice",
    answer: "",
    title: "",
    isflag: false,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 23,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 5,
  },
  {
    id: 24,
    questiontype: "Equation",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 1,
  },
  {
    id: 25,
    questiontype: "SortingQuestion",
    answer: "",
    title: "",
    isflag: false,
    progress: "notdone",
    attempts: 1,
  },
  {
    id: 26,
    questiontype: "SingleChoiceQuestion",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 27,
    questiontype: "FillInTheBlank",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 2,
  },
  {
    id: 28,
    questiontype: "MatrixSortingQuestion",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 2,
  },
  {
    id: 29,
    questiontype: "MultipleChoice",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 30,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 3,
  },
  {
    id: 31,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 32,
    questiontype: "FreeChoice",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 5,
  },
  {
    id: 33,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 34,
    questiontype: "Equation",
    answer: "",
    title: "",
    isflag: true,
    progress: "done",
    attempts: 4,
  },
  {
    id: 35,
    questiontype: "SortingQuestion",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 36,
    questiontype: "SingleChoiceQuestion",
    answer: "",
    title: "",
    isflag: true,
    progress: "done",
    attempts: 4,
  },
  {
    id: 37,
    questiontype: "FillInTheBlank",
    answer: "",
    title: "",
    isflag: true,
    progress: "notdone",
    attempts: 4,
  },
  {
    id: 38,
    questiontype: "MatrixSortingQuestion",
    answer: "",
    title: "",
    isflag: false,
    progress: "done",
    attempts: 4,
  },
  {
    id: 39,
    questiontype: "MultipleChoice",
    answer: "",
    title: "",
    isflag: false,
    progress: "notdone",
    attempts: 6,
  },
  {
    id: 40,
    questiontype: "SimpleInput",
    answer: "",
    title: "",
    isflag: true,
    progress: "done",
    attempts: 4,
  },
];
